language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

addons:
  postgresql: "12.0"

before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -U postgres -d testdb -f test/testdb.sql
