language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -U postgres -d testdb -f test/testdb.sql
