language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

before_script:
  - psql -U postgres -d testdb -f test/testdb.sql

addons:
  postgresql: "12.0"
