language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE testdb;' -U postgres
  - node db/migrations.js
  - node db/seeder.js

services:
  - postgresql
addons:
  postgresql: "9.6"
